server:
  port: 8081
  servlet:
    context-path: /


# 连接数据库的配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  devtools:
    restart:
      enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wukong.logisticsproject.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false